### ISSUE TITLE
Sorting causes "Page not Found" on one specific Book

### ISSUE THREAD

**Issue by cpressland** [ssddanbrown/BookStack#100]
We have a book titled Infrastructure, if I attempt to sort any page within the book I receive a 'Page not Found' message. All other books seemingly work fine, additionally everything works if I create a new book. See attached screen cap. It's also worth noting that this was the first book we created when we first deployed BookStack, so maybe something has changed between versions? We're running on the latest 'release' commit.

[BookStack Sorting.zip](https://github.com/ssddanbrown/BookStack/files/221037/BookStack.Sorting.zip)

OS: CentOS 7.2
Nginx 1.8.1
PHP: 7.0.5
MariaDB: 10.1.13

I'm not sure what logging you may or may not need for this, but Nginx logging reports nothing of consequence other than page access.

**Comment by ssddanbrown** [comment]
Hi @cpressland, Thanks for reporting this bug and sorry about this.

I have a suspicion this is occurring when there's a draft page on a book. I'll test to confirm this and hopefully fix this tonight. If I fix this I'll publish a bugfix release for this and #97.

**Comment by ssddanbrown** [comment]
@cpressland I've now updated the release branch with a fix for this so will close this issue. If the fix does not resolve this issue for you let me know and I'll re-open this.
