### ISSUE TITLE
ctrl+z return to top of page

### ISSUE THREAD

**Issue by Di2g10** [ssddanbrown/BookStack#107]
Just a Small possible issue / iritation. When i Undo an entry using ctrl + Z my view is moved to the top of the screen or just up. Would be best if the screen stayed on the current view so long as the change was on the current view.

**Comment by ssddanbrown** [comment]
Hi @Di2g10, I'm having trouble being able to replicate this issue. Can you provide exact steps along with details of what browser you're using?

**Comment by ssddanbrown** [comment]
I'm going to close this for now, If you still find the issue and can produce steps to replicate we'll re-open this issue.
