### ISSUE TITLE
No scrollbar on Markdown preview in Firefox

### ISSUE THREAD

**Issue by davidtorcivia** [ssddanbrown/BookStack#111]
On BookStack v0.9.3, when the markdown editor is enabled, if the text length extends past the screen no scrollbar appears. You can still scroll manually, but the markdown editor fills the screen and you cannot scroll back up to the header (to save draft/page/etc). 

Bug seems to be related to the "preview" part of the page because, when writing a fresh page, if only the editor side goes past the screen break, then a scrollbar appears on the editor side without issue. If the preview side goes past the bottom of the screen, however, the scrollbar never appears, the edit window moves up, and you soon can't scroll out of it.

Tested this bug and found present on latest firefox on Win 8.1, OSX, and Fedora 23 with a fresh profile with addons disabled.

Easiest way to reproduce is to enable markdown editor, open firefox, and paste in a large amount of text into the editor.

**Comment by fredericmohr** [comment]
I'm having the same problem. I currently have to use chrome just for BookStack. It works, but I'd rather stick with one browser.
