### ISSUE TITLE
Standardise Role/User Delete Button Format/Aesthetics

### ISSUE THREAD

**Issue by cpressland** [ssddanbrown/BookStack#114]
Hi,

Currently a Delete button does not exist on the users properties page, would be great if we could remove people rather than just set a random passwords against them to prevent access.

Thanks,
Chris Pressland

**Comment by cpressland** [comment]
I just found this on the page below the banner, in which case, can we modify this to make it a red button like on the roles page?

**Comment by ssddanbrown** [comment]
@cpressland Sure, I'll update the issue title to be specific to the new request and mark this for the next release.
