### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by winiciuslima** [ssddanbrown/BookStack#116]
I followed all the steps required in the documentation, but you can not install always the error database creation. 
The following errors are:

```
  [Illuminate \ Database \ QueryException]
   SQLSTATE [HY000]: General error: 1214 The used table type does not support FU
   LLTEXT indexes (SQL: ALTER TABLE ADD FULLTEXT search pages (name, text))
```

```
[PDOException]
   SQLSTATE [HY000]: General error: 1214 The used table type does not support FU
   LLTEXT indexes
```

I have another doubt this system is based on NodeJS as reported in the description of the project, being necessary installation on the server?

**Comment by leomartinez** [comment]
Are you using MySQL prior to version **5.6**?
The prerequisite of MySQL 5.6 is because prior versions don't support FULLTEXT indexes in InnoDB databases. 
In debian 8 (which I used for my installation) you can add the [official APT repository](https://dev.mysql.com/downloads/repo/apt/) to install MySQL 5.6.

**Comment by ssddanbrown** [comment]
Hi @winiciuslima,
As said above, It's most likely you are using and older MySQL version that does not support FullText indexes. To add to what @leomartinez has said, If you are using Ubuntu 14.04 I believe you can get MySQL in the default repos by installing `mysql-server-5.6` (Or something similar).
Alternatively I think MariaDB 10.0 and above is also compatible.

NodeJS is not a standard requirement. It's required to build the CSS & JS when not using the `release` branch so is only really need during development & testing.

**Comment by winiciuslima** [comment]
Updated the mysql version 5.6 and the database installation occurred correctly, but when trying to access the system the link is redirected to /login and the message of page not found.
I think it may be something related to my documentRoot is directed to the folder /public.

**Comment by ssddanbrown** [comment]
Are you able to post your apache/nginx configuration for BookStack?

**Comment by winiciuslima** [comment]
Apache!

**Comment by TechMisha** [comment]
Hi @ssddanbrown,
I think it's better to make small changes in the migrations to solve this problem - add a `$table->engine = 'MyISAM';` in migrations files:

- 2015_07_12_114933_create_books_table.php
- 2015_07_12_190027_create_pages_table.php
- 2015_07_27_172342_create_chapters_table.php

[patch.diff](https://gist.github.com/TechMisha/74a0ad73a782cc5c03c0321c5ef2b7a0)

**Comment by ssddanbrown** [comment]
@TechMisha Thanks for your patch but I don't think that's the answer to this particular issue. Also, Your solution is already suggested in pull request #118, You can find my thoughts on it there.

@winiciuslima Here are some instructions for debugging:
https://www.bookstackapp.com/docs/admin/debugging

Can you follow those to see if you can get any debug messages or see if you can anything in you log file?

**Comment by winiciuslima** [comment]
I managed to fix the problem, checked all the steps again and all permissions and files within a folder was not with the correct permission for this reason was happening the error.
Request: I would ask if possible change the version of MySQL because that version 5.6 is too heavy for beginners requiring at least one server with 2G memory.

**Comment by ssddanbrown** [comment]
@winiciuslima Awesome! Glad to hear you found the issue. I'll go ahead and close this issue now.

I'm not going to change the requirements just for that reason. MySQL 5.6 *(And BookStack with all its dependencies)* can work perfectly fine on a 512MB VPS. It may just take a little extra configuration (Setting `performance_schema=0` i think) to make it not hog memory.
