### ISSUE TITLE
Page availability across multiple books and chapters

### ISSUE THREAD

**Issue by davidPilkington** [ssddanbrown/BookStack#122]
Reading through the discussion on #48 I'm not sure where the discussion of being able to reference a page in multiple books went. Is this something that is being considered?

**Comment by Di2g10** [comment]
is this not handled by the attribute system?

**Comment by davidPilkington** [comment]
Possibly. Not sure how that works in the editor. I have tried adding a hyperlink, but I am not quite sure how I point to another page other than getting the entire link for that page and pasting it to the url field. Is that how this works? Or is the attribute system only available in markup editor?
