### ISSUE TITLE
Not able to run after installation

### ISSUE THREAD

**Issue by rosinghal** [ssddanbrown/BookStack#132]
Attached the apache error_log.

[error_log.txt](https://github.com/ssddanbrown/BookStack/files/323350/error_log.txt)

**Comment by ssddanbrown** [comment]
Hi @rosinghal,
I noticed in your log that you're trying to access BookStack within a sub directory. Currently BookStack requires being at the URL root (On it's own domain or sub-domain). That could be the cause of your issues.

**Comment by rosinghal** [comment]
Still same error. It gets redirected to login page with error "Whoops, looks like something went wrong". Though error page works just fine.

**Comment by ssddanbrown** [comment]
[Here's some instructions for debugging errors.](https://www.bookstackapp.com/docs/admin/debugging). Could you turn on debug mode and see what error displays?

**Comment by rosinghal** [comment]
Here is html file after enabling debug.
[login.html.zip](https://github.com/ssddanbrown/BookStack/files/324926/login.html.zip)

**Comment by ssddanbrown** [comment]
Looks like this is likely xDebug causing this.
You could try finding and changing `xdebug.max_nesting_level` php setting to `200` and see if that fixes things.

**Comment by rosinghal** [comment]
Thanks. It worked.

On Tue, Jun 21, 2016 at 1:08 PM, Dan Brown <notifications@github.com> wrote:

> Looks like this is likely xDebug causing this.
> You could try finding and changing xdebug.max_nesting_level php setting
> to 200 and see if that fixes things.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ssddanbrown/BookStack/issues/132#issuecomment-227363629>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ADUfXk6csj7ZQ1yAqVtHcEUrqg2E5IEEks5qN5TagaJpZM4I5pXN>
> .
>



-- 
Regards,
Rohit Singhal
