### ISSUE TITLE
Installation Issue - Missing Manifest

### ISSUE THREAD

**Issue by cshoare** [ssddanbrown/BookStack#133]
Hi,

I have tried to install the software locally on a XAMPP server but the first time I tried to navigate to it I got the following error:

> ErrorException in helpers.php line 17:
file_get_contents(C:\xampp\htdocs\BookStack\public\build/manifest.json): failed to open stream: No such file or directory (View: C:\xampp\htdocs\BookStack\resources\views\base.blade.php) (View: C:\xampp\htdocs\BookStack\resources\views\base.blade.php)

It has been set-up to run on the following (local virtual host) url http://www.bookstack.dev:801/ 

The mentioned file "manifest.json" does not appear to have been created, would this normally be set-up during the installation? 

Any help will be much appreciated. 

Thanks,
cshoare

**Comment by ssddanbrown** [comment]
Hi @cshoare,
This would happen if you clone the master branch of the project.

Can you try using the release branch?

**Comment by cshoare** [comment]
Hi, sorry you are completely correct. 

I pulled from the wrong location. 

Really like the system so far. 

Thanks,
cshoare
