### ISSUE TITLE
Can't Delete Images (500 Error) in Firefox/Chrome

### ISSUE THREAD

**Issue by fredericmohr** [ssddanbrown/BookStack#136]
We're using Bookstack (commit: be711215e833358acfce994fa80141e99c2e9664) and we're experiencing problems when trying to delete images in both Firefox and Chrome.

![screenshot_20160629_112714](https://cloud.githubusercontent.com/assets/5955966/16447518/53bb0cf4-3ded-11e6-9b80-3e062e13fe2b.png)

The laravel.log shows the following, hope this helps resolving this issue. Let me know if I can provide any additional info.

    [2016-06-29 09:24:29] production.ERROR: exception 'ErrorException' with message 'Argument 1 passed to BookStack\Services\PermissionService::checkEntityUserAccess() must be an instance of BookStack\Entity, instance of BookStack\Image given, called in /var/www/BookStack/app/helpers.php on line 48 and defined' in /var/www/BookStack/app/Services/PermissionService.php:314
    Stack trace:
    #0 /var/www/BookStack/app/Services/PermissionService.php(314): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(4096, 'Argument 1 pass...', '/var/www/BookSt...', 314, Array)
    #1 /var/www/BookStack/app/helpers.php(48): BookStack\Services\PermissionService->checkEntityUserAccess(Object(BookStack\Image), 'image-delete')
    #2 /var/www/BookStack/app/Http/Controllers/Controller.php(96): userCan('image-delete', Object(BookStack\Image))
    #3 /var/www/BookStack/app/Http/Controllers/ImageController.php(160): BookStack\Http\Controllers\Controller->checkOwnablePermission('image-delete', Object(BookStack\Image))
    #4 [internal function]: BookStack\Http\Controllers\ImageController->destroy(Object(BookStack\Repos\PageRepo), Object(Illuminate\Http\Request), '92')
    #5 /var/www/BookStack/bootstrap/cache/compiled.php(9309): call_user_func_array(Array, Array)
    #6 /var/www/BookStack/bootstrap/cache/compiled.php(9371): Illuminate\Routing\Controller->callAction('destroy', Array)
    #7 /var/www/BookStack/bootstrap/cache/compiled.php(9351): Illuminate\Routing\ControllerDispatcher->call(Object(BookStack\Http\Controllers\ImageController), Object(Illuminate\Routing\Route), 'destroy')
    #8 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
    #9 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
    #10 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
    #11 /var/www/BookStack/bootstrap/cache/compiled.php(9828): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
    #12 /var/www/BookStack/bootstrap/cache/compiled.php(9352): Illuminate\Pipeline\Pipeline->then(Object(Closure))
    #13 /var/www/BookStack/bootstrap/cache/compiled.php(9339): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(BookStack\Http\Controllers\ImageController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'destroy')
    #14 /var/www/BookStack/bootstrap/cache/compiled.php(8420): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'BookStack\Http\...', 'destroy')
    #15 /var/www/BookStack/bootstrap/cache/compiled.php(8407): Illuminate\Routing\Route->runController(Object(Illuminate\Http\Request))
    #16 /var/www/BookStack/bootstrap/cache/compiled.php(8121): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
    #17 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
    #18 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
    #19 /var/www/BookStack/app/Http/Middleware/Authenticate.php(47): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
    #20 [internal function]: BookStack\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
    #21 /var/www/BookStack/bootstrap/cache/compiled.php(9838): call_user_func_array(Array, Array)
    #22 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
    #23 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
    #24 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
    #25 /var/www/BookStack/bootstrap/cache/compiled.php(9828): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
    #26 /var/www/BookStack/bootstrap/cache/compiled.php(8122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
    #27 /var/www/BookStack/bootstrap/cache/compiled.php(8113): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
    #28 /var/www/BookStack/bootstrap/cache/compiled.php(8103): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
    #29 /var/www/BookStack/bootstrap/cache/compiled.php(2400): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
    #30 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
    #31 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
    #32 /var/www/BookStack/bootstrap/cache/compiled.php(3176): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
    #33 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
    #34 /var/www/BookStack/bootstrap/cache/compiled.php(9838): call_user_func_array(Array, Array)
    #35 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
    #36 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
    #37 /var/www/BookStack/bootstrap/cache/compiled.php(13274): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
    #38 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
    #39 /var/www/BookStack/bootstrap/cache/compiled.php(9838): call_user_func_array(Array, Array)
    #40 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
    #41 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
    #42 /var/www/BookStack/bootstrap/cache/compiled.php(11822): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
    #43 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
    #44 /var/www/BookStack/bootstrap/cache/compiled.php(9838): call_user_func_array(Array, Array)
    #45 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
    #46 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
    #47 /var/www/BookStack/bootstrap/cache/compiled.php(13009): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
    #48 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
    #49 /var/www/BookStack/bootstrap/cache/compiled.php(9838): call_user_func_array(Array, Array)
    #50 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
    #51 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
    #52 /var/www/BookStack/bootstrap/cache/compiled.php(12946): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
    #53 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
    #54 /var/www/BookStack/bootstrap/cache/compiled.php(9838): call_user_func_array(Array, Array)
    #55 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
    #56 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
    #57 /var/www/BookStack/bootstrap/cache/compiled.php(3237): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
    #58 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
    #59 /var/www/BookStack/bootstrap/cache/compiled.php(9838): call_user_func_array(Array, Array)
    #60 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
    #61 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
    #62 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
    #63 /var/www/BookStack/bootstrap/cache/compiled.php(9828): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
    #64 /var/www/BookStack/bootstrap/cache/compiled.php(2347): Illuminate\Pipeline\Pipeline->then(Object(Closure))
    #65 /var/www/BookStack/bootstrap/cache/compiled.php(2331): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
    #66 /var/www/BookStack/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
    #67 {main}

**Comment by ssddanbrown** [comment]
@fredericmohr Sorry about this bug and thanks for picking it up. The fix will be in the next release, Likely to be released on Sunday.

**Comment by fredericmohr** [comment]
Awesome, thanks for the quick fix :)
