### ISSUE TITLE
BookStack as a Package

### ISSUE THREAD

**Issue by z2z** [ssddanbrown/BookStack#141]
This is simply amazing. Wanted to something to quickly create help document inside existing application.

It would be great  if this can be developed as separate laravel package in future.

**Comment by ssddanbrown** [comment]
Hi @z2z,
Thanks for the suggestion and sorry I did not come back to you earlier. 

I've had a think about this and I'm not sure this will be possible without sacrificing development of BookStack in some sort of way. There's a lot of core components such as authentication , authorisation and configuration that I think would conflict with an application if BookStack was to be packaged. I like the fact these components are tightly coupled into the documentation side of BookStack as it means a cohesive experience can be provided.  

Also, It would require a lot of work to continuously ensure package API compatibility. I like the idea overall but I think it would add too much work. Hopefully those developing docs inside their application still find the BookStack source to be a handy repository of examples.

Sorry this is not the answer you ideally wanted to hear.
