### ISSUE TITLE
Back-to-top button does not work on Firefox

### ISSUE THREAD

**Issue by ssddanbrown** [ssddanbrown/BookStack#153]

**Comment by jeffshead** [comment]
Not working in Firefox, again. I'm using BookStack v22.11.1 in a Docker container.

The button does not appear on any page on my site nor on this page of the demo site when using Firefox:
https://demo.bookstackapp.com/books/bookstack-demo-site/page/mixed-content-example-page

I tested with two different Firefox browsers. The button does display in Chrome.

I also tested two other BookStack installs that I found on the Internet.
https://bookstack.surrey.ac.uk/books/rcs-user-guides/page/sftp-using-accesseps-to-transfer-files#bkmrk-sftp
https://docs.punctumbooks.com/books/usage-data/page/monthly-data-collection-and-preparation

The button does display in Firefox on those two sites so I'm guessing those sites must be using BookStack versions that are not affected by this bug.
