### ISSUE TITLE
Feature Request: Ability to Assign/Restrict Roles to Certain Books

### ISSUE THREAD

**Issue by matt-sawyers** [ssddanbrown/BookStack#157]
Desired Feature:
Ability to assign/restrict roles for certain books. 

I create documentation for non-profits. It would be nice to allow upper-management to view all books and allow volunteers to only see certain books. Similar to Lessons Learned Server:
https://www.dropbox.com/s/edb7f3xab9kzmr0/Screenshot%202016-08-02%2004.29.43.png?dl=0

**Comment by ssddanbrown** [comment]
Hi @matt-sawyers,
Thanks for your request. Have you tried using the built-in roles & permissions system in BookStack at all and ,if so, How is it limited for your uses?

Roles can set up in the settings area of BookStack and permissions can be changed on each Book, Chapter and Page via the dropdown menu (3 dots icon) at the top right of the toolbar (Near the edit button). Permissions cascade down from books to chapters to pages.

**Comment by matt-sawyers** [comment]
I've actually not tried it yet. I just didn't see the option in the demo (or at least I didn't think I saw it). I'm working on installing Bookstack today and will give what you said a try.

**Comment by ssddanbrown** [comment]
Hi again @matt-sawyers, I will go ahead and close this issue. If BookStack is missing some role features you need just reply and we can re-open this or create a new issue.
