### ISSUE TITLE
Installation in subdirectory

### ISSUE THREAD

**Issue by fkonietzny** [ssddanbrown/BookStack#163]
### For Bug Reports
PHP Version: 5.5.9

MySQL Version: 5.5.50-0ubuntu0

Expected Behavior:
in .env I added the APP_URL=https://example.net/apps/bookstack
after runnung "composer install && php artisan migrate" the static content is still 
requested from https://example.net/ e.g. https://example.net/logo.png  instead of https://example.net/apps/bookstack/logo.png

Is it possible to install BookStack in a subdirectory, if yes - what did I miss?

thanks in advance!

Actual Behavior:

**Comment by ssddanbrown** [comment]
Hi @fkonietzny,
This functionality is currently not possible but is already requested under #40 so I will close this issue since it's a duplicate.

On another note,  BookStack is only really supported for MySQL 5.6+.
