### ISSUE TITLE
jQuery/TinyMCE error on fresh install

### ISSUE THREAD

**Issue by JulienRamel** [ssddanbrown/BookStack#167]
Hi,

Actual Behavior: on a fresh install of BookStack (v0.11.1) with Google Chrome on Mac, I created a new book and a new page. On this page edition, I can set some styles with keyboard shortcuts (cmd+B for bold, etc) but when I want to add a link by selecting a text and clicking on the "link" TinyMCE icon, I got an error. Idem on clicking all the other buttons : images, tables, colors, etc.

`Uncaught TypeError: Cannot read property 'ownerDocument' of undefined
tinymce.min.js?ver=4.3.7:11`

Expected Behavior: clicking on TinyMCE buttons should work properly on Google Chrome. **Note that it works on Firefox 41.0.2 on Mac.**

OS: Debian GNU/Linux 8.5 (jessie)
PHP Version: PHP 7.0.9-1~dotdeb+8.1
MySQL Version: 15.1 Distrib 10.0.26-MariaDB
BookStack Version: v0.11.1
Browser Version: Google Chrome Version 51.0.2704.106 (64-bit) / OSX

**Comment by ssddanbrown** [comment]
Hi @JulienRamel,

Can you login to the [BookStack demo instance](https://www.bookstackapp.com/#demo) and let me know if you can re-produce the issue in the editor there aswell?

If that does not work could you also test on [this TinyMCE example page here](https://www.tinymce.com/docs/demo/basic-example/) and let me know the results.

**Comment by JulienRamel** [comment]
Hi @ssddanbrown, I also have the issue on the BookStack demo instance but not on the TinyMCE example page.

**Comment by ssddanbrown** [comment]
Hi @JulienRamel, For BookStack v0.12.1 I have updated TinyMCE to a newer version. Could you give it another go? I've updated the demo instance to the latest version so you can try on there again to test the updated version.

If it still doesn't work in chrome can you try in an incognito window (So any/most plugins are disabled) just to rule those out? I've given v0.12.1 a quick test using BrowserStack (Don't have a mac to hand) and all appeared fine from my quick testing.

**Comment by JulienRamel** [comment]
Hi @ssddanbrown, I tested on Chrome on the demo application with BookStack v0.12.1 and it works great 👍 *But* I'm now on Chrome 52...

**Comment by ssddanbrown** [comment]
Okay, Good news, I'll mark this as closed for now then. Just shout if you have any other issues on Chrome/Mac.
