### ISSUE TITLE
Add a 'remember me' option to login

### ISSUE THREAD

**Issue by ssddanbrown** [ssddanbrown/BookStack#17]

**Comment by ssddanbrown** [comment]
Added in bd73c88eddb946d9318f2a5f45b5a701771328d8

**Comment by Zyzto** [comment]
this seems to be missing in current releases

**Comment by c0nfus3d** [comment]
Was this never merged with the master?

**Comment by ssddanbrown** [comment]
This option still exists, It's not however part of LDAP or SAML login.

**Comment by Zyzto** [comment]
@ssddanbrown I see is it possible in the future to be added ? 

as well is there way to increase token/cookies TTL? currently

**Comment by ssddanbrown** [comment]
@Zyzto A "remember me" option gets more complicated for external auth as it'd have to be optional to adhere to the wishes of those auth systems and I'm not a fan of options for options. Think it has been requested elsewhere though.

You should be able to control the session lifetime via the `SESSION_LIFETIME` env option as shown here:

https://github.com/BookStackApp/BookStack/blob/master/.env.example.complete#L74
