### ISSUE TITLE
Flexible containers are not collapsible

### ISSUE THREAD

**Issue by montharon** [ssddanbrown/BookStack#172]
All flexible containers like the "Toggle details" feature are not collapsible (any more).
This is also true for the chapter/page sorting and the little arrow besides the "pages link"
![flexcontainer](https://cloud.githubusercontent.com/assets/21140797/17939695/0fc4cc68-6a2c-11e6-8112-c58349e36cc4.PNG)

**Comment by ssddanbrown** [comment]
@montharon I'm guessing that you've got bookstack installed on a url sub-directory and that `debug` is still true in the `.env` file?

If so this is a problem with the debugbar not loading in correctly when on a url sub-dir which breaks jQuery which is causing the mentioned issues.

**Comment by montharon** [comment]
@ssddanbrown Many thanks for your quick reply!
The issue can be closed since it was definitely the debugging option ;)
Set it back to false and now it works like intended...
