### ISSUE TITLE
Completely empty page on Android mobile device

### ISSUE THREAD

**Issue by montharon** [ssddanbrown/BookStack#173]
All pages viewed on an Android mobile device are completeley empty/blank/white.
There is no content at all except the "Book Navigation" (table of contents) and the top navigation.

**Comment by ssddanbrown** [comment]
@montharon I've just double checked on a nexus 5x, Android 7, Chrome and have not got the mentioned issue. Can you see the same issue on the [BookStack demo instance](https://demo.bookstackapp.com)?

Can you specify your android device, android version and browser used?

**Comment by montharon** [comment]
@ssddanbrown Hi Dan again ;)
I can clearly see the same issue also on the demo site!

I'm using a OnePlusOne with CyanogenMod 13.0-20160816 (only a few days old) [Android 6.0.1] and their new Gello Browser....

**Comment by ssddanbrown** [comment]
@montharon Ah, Okay, I don't really officially support Gello but I've download APK and tested BookStack on Gello. It appears the page content fade in animation is not fully supported on Gello which is leaving it blank. You can override this to make it appear again by pasting the following in the 'Custom HTML head' setting of BookStack:

```
<style>
.anim.fadeIn {
 opacity: 1;
}
</style>
```

We'll leave this issue open though and remove such animations from any critically important content (such as page content) in a future release to cover this and in to cover other browsers that could possibly have the same issue.

**Comment by montharon** [comment]
@ssddanbrown Ahhhh, that did the trick! As always, many thanks for your great support! It is much appreciated!
