### ISSUE TITLE
Some small CSS improvements

### ISSUE THREAD

**Issue by montharon** [ssddanbrown/BookStack#174]
Did a small CSS improvements for me:

`.page-content {
max-width: 100%
}
.page-content table {
word-break: normal;
}
.tag-display {
margin: 32px 18px;
}`

(1) The max-width command uses much more space for the content instead of limiting the width to a certain pixel value.
(2) The word-break "word" was not recognized from Firefox (inspected the code with Firebug), so the wordwrapping looked strange.
(3) The margin of the tag-display box was changed, just to have more space between the content and the box.

Just my suggestions ;)
montharon

**Comment by ssddanbrown** [comment]
Hello again @montharon, Thanks for the css recommendations, Here's my views:

1. The max-width is really a user preference so I don't want to force it at 100% at an application level. Keeping content at a fixed max-width keeps the page a bit neater and looks more inviting to new users. At some point soon I'd like to add it as a user preference so each user can choose whatever suits them.
2. As of v0.12.1 this is now implemented :smile: .
3. As of v0.12 I've added a little more padding around the tag box. At some point I want to move this out  of the content anyway but this is a nice tweak for now.

Thanks again!
Dan
