### ISSUE TITLE
Improvement: Autogenerated Page Index

### ISSUE THREAD

**Issue by riorii** [ssddanbrown/BookStack#178]
It would be nice that an index would be generated based on Header-1 lines, something like wiki do.
Also the indexes would have to have links to the section, so when you click you would see the complete section.

**Comment by pydubreucq** [comment]
Hi,
I think it's the same issue than [68](https://github.com/ssddanbrown/BookStack/issues/68)
Best regards

**Comment by riorii** [comment]
Totally right @pydubreucq! Thanks!
