### ISSUE TITLE
Improvement: Add checkbox "Public" - Custom permissions

### ISSUE THREAD

**Issue by riorii** [ssddanbrown/BookStack#188]
When "Allow public viewing?" is check on general settings, if custom permissions are set, that book/page/chapter become non public.

Example: 
user 1, role 1
user 2, role 2
*Allow public viewing enable

1) user 1 create a book -> book is public for all but user 2 can't edit it.
2)  Enable custom permissions over that book and give role 2 edit permissions.
3) user 2 can edit it but the book is not more public.

The solution maybe would be adding a checkbox at custom permission that tag the book/chapter/page as public when you enable custom permissions.

**Comment by riorii** [comment]
I think this is the same as #138 . If is the same please close it! Thanks!!

**Comment by ssddanbrown** [comment]
Hey @riorii, Yep, It's essential the same request! I was just typing that out in a response when I saw your additional comment :smile:. I will therefore close this issue.
