### ISSUE TITLE
Page PDF Export

### ISSUE THREAD

**Issue by ssddanbrown** [ssddanbrown/BookStack#31]

**Comment by THS-on** [comment]
Maybe add not only PDF-Export. A BookStack specific Import and Export would be nice.

Reddit question: https://www.reddit.com/r/selfhosted/comments/3z06rb/bookstack_a_free_wikilike_information_store/cypkdi1

**Comment by ssddanbrown** [comment]
Potentially solve this using this library:
https://github.com/mikehaertl/phpwkhtmltopdf

**Comment by ssddanbrown** [comment]
@THS-on Definitely something I'm looking to add. I've opened a separate issue, #43 , for system export/imports.

**Comment by ssddanbrown** [comment]
Added in PDF export in commit 080acf0a6234952b4eac1df59e9c11d3be04074b and this has been included in release 0.7
