### ISSUE TITLE
View of new and updated articles

### ISSUE THREAD

**Issue by Di2g10** [ssddanbrown/BookStack#46]
Would be nice to see which articles have been added recently or significantly updated recently.
Also would be nice to be notified or have an easy way to see if pages that i have created are edited by other users.

**Comment by ssddanbrown** [comment]
Recently updated and created pages can now be seen on the homepage. The headings can than be clicked through to get full listings. I've also compacted the lists on the homepage to give a better initial overview after logging in to a BookStack instance. Here's a screenshot of the new homepage:

![image](https://cloud.githubusercontent.com/assets/8343178/13198549/d0cb7328-d803-11e5-82b6-555985088721.png)

I have not yet done the bonus part of this issue as I would like to roll that idea up into a full custom-querying interface. I'll open a new issue for that.

**Comment by ssddanbrown** [comment]
#64 Is the new issue mentioned above.
