### ISSUE TITLE
admin@admin.com gets created without a password.

### ISSUE THREAD

**Issue by cpressland** [ssddanbrown/BookStack#51]
Hi,

I've noticed that since the last commit that the default admin@admin.com user doesn't seem to get generated with a password anymore on a fresh install.

```
MariaDB [bookstack_db]> select * from users;
+----+-------+-----------------+----------+----------------+---------------------+---------------------+-----------------+----------+------------------+
| id | name  | email           | password | remember_token | created_at          | updated_at          | email_confirmed | image_id | external_auth_id |
+----+-------+-----------------+----------+----------------+---------------------+---------------------+-----------------+----------+------------------+
|  1 | Admin | admin@admin.com |          | NULL           | 2016-02-01 15:19:15 | 2016-02-01 15:19:15 |               1 |        0 |                  |
+----+-------+-----------------+----------+----------------+---------------------+---------------------+-----------------+----------+------------------+
1 row in set (0.00 sec)
```

I had to manually issue the following before I was able to login for the first time.

```
UPDATE users SET password="$2y$10$6LoV1WoLVs4gylUoqhc9Xe/0.VuP/1YTxq3/8jiMcVW.oYSvIlfrC" where id=1;
```

Note that I'm testing the deployments with my own [cookbook](https://github.com/cpressland/bookstack) so it could be a bug in that, but running the deployment manually seems to produce the same result.

**Comment by ssddanbrown** [comment]
Thanks for raising this issue. Is now fixed as of 4bb7f0613fd3bf672ca8c3042ad08e9b7ace5458. Will ensure I test from a clean install before pushing a new release in the future.

Sorry for any hassle this caused anyone.
