### ISSUE TITLE
Error when upload image 

### ISSUE THREAD

**Issue by Kilhog** [ssddanbrown/BookStack#52]
Hi, 
When I upload a image, I have this : 
![capture d ecran 2016-02-03 a 14 00 30](https://cloud.githubusercontent.com/assets/4045682/12782932/9b25afe6-ca7e-11e5-98ee-0d8c8f7ac9ae.png)

The message in the error is : 
`<h1>Whoops, looks like something went wrong.</h1>`

But the uploaded image is present in : `public/uploads/images/gallery/2016-02-Feb/my-image.jpg`
And for information my vhost is : 
```
<VirtualHost *:80>
    ServerName bookstack.dev
    DocumentRoot "/var/www/BookStack/public/"

    <Directory "/var/www/BookStack/">
        Options FollowSymLinks MultiViews
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>
```
Do you know why ? 

Thank's

**Comment by brandonhamilton** [comment]
Are you sure you have the GD extension for php installed ?

**Comment by Kilhog** [comment]
GD is on, but I just saw the pictures ".png" works, but not the ".jpg".
And in my GD configuration the .jpg support is not enabled, So I think is that, thanks :+1: 
```
gd

GD Support => enabled
GD Version => bundled (2.1.0 compatible)
GIF Read Support => enabled
GIF Create Support => enabled
PNG Support => enabled
libPNG Version => 1.2.50
WBMP Support => enabled
XBM Support => enabled

Directive => Local Value => Master Value
gd.jpeg_ignore_warning => 0 => 0
```

**Comment by Kilhog** [comment]
I add the jpeg support for GD, and it works perfectly. thank you :)

**Comment by ssddanbrown** [comment]
Glad to hear your found a solution to this issue. Thanks @brandonhamilton for helping to solve this.

I'll add GD to the install requirements.
