### ISSUE TITLE
Text hover image on PDF export

### ISSUE THREAD

**Issue by fabienlege** [ssddanbrown/BookStack#53]
- Go to official demo to this page : https://demo.bookstackapp.com/books/dummy-content-book/page/another-example-of-various-content
- click export to PDF
- In the PDF, text is hover image

here the PDF generated by demo : 
[another-example-of-various-content.pdf](https://github.com/ssddanbrown/BookStack/files/115971/another-example-of-various-content.pdf)

**Comment by ssddanbrown** [comment]
Thanks for spotting this bug. The above commit that fixes this has now been merged into the latest release. I've removed the floats for now to provide a less broken result. I'd ideally like the PDF to look as per the page but I don't want to complicate the install process with extra requirements to persue a perfect PDF output so I'm happy with the results for now.
