### ISSUE TITLE
LDAP - not using uid

### ISSUE THREAD

**Issue by smithkyle** [ssddanbrown/BookStack#56]
We use ActiveDirectory for our directory services, and are not using the uid field. As a result, we cannot login using ldap auth because it results in the following error:

`at HandleExceptions->handleError('8', 'Undefined index: uid', '/var/www/html/app/Services/LdapService.php', '49',`

Please let me know if you need any additional info.

**Comment by ssddanbrown** [comment]
The above commit that will hopefully fix this has been merged into release. BookStack will now use the provided 'dn' if no 'uid' is provided. Let me know if this still doesn't solve the issue. Unfortunately I do not have ActiveDirectory to test against.

**Comment by smithkyle** [comment]
Works perfect! Thank you!
