### ISSUE TITLE
Markdown Editor

### ISSUE THREAD

**Issue by nwalke** [ssddanbrown/BookStack#57]
I would love to have the page editor be a markdown editor, maybe with a preview next to it.

**Comment by nwalke** [comment]
@ssddanbrown I've been thinking about how best to implement this... do you think it should just be a system wide setting?  I imagine not everyone wants this, but I wonder if it makes sense to enable/disable it at a system level or a per page level.

**Comment by ssddanbrown** [comment]
I would say system-level as it could confuse people going from one editor to another depending on what page they edit.

I've actually been eager to get some sort of markdown importing working for BookStack so we can have a 'BookStack docs' repo which would then be frequently imported to a BookStack instance at docs.bookstackapp.com.

**Comment by nwalke** [comment]
So one would have a repo full of markdown content that bookstack just then displays?  That would be pretty cool, but then you might as well just use the Github wiki repo :/

**Comment by ssddanbrown** [comment]
Yeah, but by importing it into BookStack it will be fully searchable. I agree it wouldn't be useful for most cases but I'd like the project documentation to be hosted on BookStack to give new users a feel for it as they learn the features and it would give the bookstackapp.com site a little more weight in search results.

That said, I'm not too sure how images would be handled with this method.

**Comment by cpressland** [comment]
Another vote for getting the markdown editor added. I'd love this, personally. Maybe it could be implemented in a similar way to how Ghost does it?

**Comment by broedli** [comment]
Oh man I totally need this!

**Comment by nwalke** [comment]
Yay!  I tried my hand at implementing this, but it was super underwhelming and looked awful.  I'm sure you'll come up with a much more elegant solution @ssddanbrown.

**Comment by broedli** [comment]
I don't want to create a new issue for this question:
The current Markdown implementation seems to be pretty basic and is missing some functionalities like task lists, intended lists, code highlighting, ...

Will you do further tweaking on this feature?

**Comment by ssddanbrown** [comment]
@broedli Absolutely, I really just wanted to get an initial implementation into BookStack to get things working with the back end systems. 

With markdown I'm never really sure where to draw the line on simplicity and features. Feel free to open new issues with specific feature requests that people can comment/vote on as it helps me see what's most wanted.
