### ISSUE TITLE
'/login' returns 500 error

### ISSUE THREAD

**Issue by ahosking** [ssddanbrown/BookStack#61]
I thought I had everything in and configured correctly but:
While Apache shows that the base url redirects correctly '/login' returns a 500 error.

My vhost for apache looks like this:

`
<VirtualHost *:80>
        ServerAdmin webmaster@localhost
        ServerName ubu1
        DocumentRoot /var/www/BookStack/public
        <Directory /var/www/BookStack/public>
                AllowOverride All
                Order allow,deny
                allow from all
        </Directory>
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
`

Any ideas?

**Comment by ssddanbrown** [comment]
Nothing immediately obvious to me, Is the 500 error from the application (in a white box) or does it look like a standard apache error message? 

If it's from the application you could try changing `APP_DEBUG` to `true` in the `.env` file to get more information. If it's from apache try looking at the apache logs in /var/log/apache2 to get more information.

**Comment by ahosking** [comment]
Oi, I missed the APP_DEBUG in the .env.

My apologies.
Got the info there that there was a rogue permission that the Apache Debug logs wasn't apparently catching.

Thanks.
