### ISSUE TITLE
Support for Attachments

### ISSUE THREAD

**Issue by cpressland** [ssddanbrown/BookStack#62]
Hey,

Would be nice to have the ability to attach files to a page that might not specifically be images. For example, a PDF.

Thanks!

**Comment by ssddanbrown** [comment]
Hi,
I've been a little wary about file upload since it can have the side effect that the content uploaded will not be indexed and part of the content like people may assume. There becomes a disconnect with knowing where the actual information you're looking for will be.

On the flip side I can understand how this would be really useful. I will look to implement this in a future release but I think it will be important that the files will be referenced as part of the flow of the page, Not just a load of links down the side or anything.

**Comment by Jk8c19** [comment]
Would it be possible to import PDF's as a page? Just have the page as a read only deal rather than attaching a PDF to a page.

**Comment by cpressland** [comment]
I agree with the comment about data not being indexed being a concern. We have documentation from various hardware vendors in PDF format which would be great to put into Bookstack. The titles would be the only thing searchable, but, needs must sometimes.

**Comment by cpressland** [comment]
This has been raised internally here again as something people want. An example given was that we may want to use BookStack to store an Excel Sheet that people may want to reference every now and then and will be updated very infrequently.

Maybe a better way of handling this would be giving Bookstack the ability to read from a specific directory somehow? Such as an SMB mounted target and present the files to the end user, read only of course? Just thinking out loud. I guess you could configure a page to show a specific directory.

**Comment by riorii** [comment]
+1 for Attachments. It would be a nice feature, giving the chance of have all docs in one platform.

**Comment by MayankTahil** [comment]
Another strong +1 for Attachments. Maybe integration with file sharing services to back end it? Just thinking out loud, integration with OwnCloud, Dropbox, GoogleDrive, or ShareFile API that stores the attachments and provides link to embed into the page. With tags associating attachments, might not even need to index the file itself or even require a viewer built in, so long as BookStack can manage the file and associate a link via drag and drop in editor would be amazing for my use case at least. Just a thought.

**Comment by garethfoote** [comment]
Another 👍  for attachments.

**Comment by mayrmartin** [comment]
👍

**Comment by BajanPro** [comment]
:+1:

**Comment by leone125** [comment]
👍

**Comment by ssddanbrown** [comment]
Base features for attachments now in and will be part of the next release :fireworks:. For any additional features or bugs regarding attachments please open a new issue.

**Comment by kopax** [comment]
Hi, I have installed 0.20.0 and I am looking how to attach a file (archife/pdf/tar) to my article, is it possible now?

**Comment by watschi** [comment]
It is possible, when editing a page just click the highlighted butten to show the attachments pane.

![grafik](https://user-images.githubusercontent.com/26351931/37816530-bd703c96-2e73-11e8-8a74-71a371b7fa64.png)

**Comment by ltoop** [comment]
I have just done a fresh install, and I don't see this button on the edit screen. What needs to be configured?
