### ISSUE TITLE
Feature Request: Memcache Support

### ISSUE THREAD

**Issue by armouredking** [ssddanbrown/BookStack#69]
So it may already have this and I just haven't figured out how to set it up. At the moment, it looks like BSA is using file caching written to ```bootstrap/cache``` using options in the ```.env``` file. I looked at Laravel's memcache setups but they didn't seem to feature the ```.env``` file itself in the reading material I perused.

It'd be nice to have it support Memcache though, in order to allow for HA and session saving. PHP provides this via [this sort of system](https://www.digitalocean.com/community/tutorials/how-to-share-php-sessions-on-multiple-memcached-servers-on-ubuntu-14-04). Using memcache in combination with unison ( just sync file stores every 5 mins with cron; gets around needing something heavy duty like ceph / gluster or offsite like Amazon ) is how I manage HA on all my other PHP apps.

**Comment by ssddanbrown** [comment]
Memcache support is baked into laravel so it'll just be a case of exposing the config to be editable via the `.env` file. I'll get this in the next release.

If you're urgent for this feature you can currently set the following variables in the `.env` file:
```
CACHE_DRIVER=memcached
SESSION_DRIVER=memcached
``` 
Then edit the `config/cache.php` file, search for memcached and you can edit the server details. Just beware this will be overwritten when you next update.
