### ISSUE TITLE
Bullet Point Issue

### ISSUE THREAD

**Issue by Di2g10** [ssddanbrown/BookStack#77]
When writing a bullet pointed list. If a bullet doesn't yet have text next to it and you mouse click on the line off that bullet, when trying to type no text is shown. However if you navigate to the bullet point using the keyboard you can enter text fine.

**Comment by ssddanbrown** [comment]
Confirmed this issue, Seems to be Firefox only. I also quickly tested in chrome and edge and could not replicate in those browsers. I will investigate further.
