### ISSUE TITLE
Cannot save draft as page

### ISSUE THREAD

**Issue by tpetrauskas** [ssddanbrown/BookStack#81]
When creating a new page or editing draft - after pressing <Save Page> shows 404.
This bug is after last release.

![notfound](https://cloud.githubusercontent.com/assets/15208933/13791866/c23c69f0-eaf7-11e5-987f-76db3698aaa1.jpg)

**Comment by ssddanbrown** [comment]
@tpetrauskas I'm having trouble replicating the issue. Please could you list the exact steps to reproduce the error?

**Comment by tpetrauskas** [comment]
Create new book
**Do not create any chapters**
Create new page
Try to save it.

Error **comes**, when trying to save **draft as page**.
Error **does not come** when trying to save **draft as draft**.

**Comment by ssddanbrown** [comment]
@tpetrauskas Still not able to replicate the issue I'm afraid.

Could you try the same steps on https://demo.bookstackapp.com/ (Login email is `admin@example.com` and password is `password`) and see if you can replicate the issue on that instance?

**Comment by tpetrauskas** [comment]
Correct, somehow it does in 1 of 2 my instances. I will do deep debug to find out what software/server component fails. My first thoughts are about slug not being generated/passed correctly.

**Comment by tpetrauskas** [comment]
Tried to compare those 2 servers, noticed that server which worked perfect used php5-mysqlnd. Installation of php5-mysqlnd in other server solved the problem.

It could be worth adding "php5-mysqlnd module" in software installation requirements.

**Comment by pdfrod** [comment]
I was having the exact same problem with version 0.9.2 and as @tpetrauskas suggested, installing "php5-mysqlnd" fixed the issue. Maybe this should be mentioned on the installation guide, as it might trip up other newbies like me.

**Comment by ssddanbrown** [comment]
Cheers, I've now added `mysqlnd` to the installation requirements.

**Comment by pdfrod** [comment]
Awesome!
