### ISSUE TITLE
Improvement: Add TimeZone Support

### ISSUE THREAD

**Issue by tpetrauskas** [ssddanbrown/BookStack#83]
It would be much more comfortable for the users to have their own TimeZone Setting in "Edit Profile" page. For an eg. different people are working in 2 separate TimeZones.

**Comment by ssddanbrown** [comment]
Hi @tpetrauskas, Thanks for the suggestion.

I'd much prefer to avoid having a setting for this but instead ensure the system localises any shown times automatically without the user having to set anything. I believe the only time shown is the draft update time which, As of the release of v0.9.0, is now localised. Let me know if you come across any other non-localized times and I will update accordingly.

**Comment by lwl12** [comment]
My server has set as UTC+8 TZ but I see UTC time stored in the database and shown as UTC time instead of UTC+8... Do I need to change APP ENV or other things to get UTC+8 display time? My PC is also in +8 TZ.
