### ISSUE TITLE
Bug: Menu Width Problem (using longer Full Name)

### ISSUE THREAD

**Issue by tpetrauskas** [ssddanbrown/BookStack#87]
This bug is happening with monitors with lower resolution (as an example 1280x800).

The screenshots have been made on 1920x1080 screen but I'm imitating the bug by using Chrome Zoom function.

## Zoom 100% - OK
![zoom - 100](https://cloud.githubusercontent.com/assets/15208933/14061722/eb7c9362-f38f-11e5-8c79-3a51c5cd08b7.png)

## Zoom 125% - OK
![zoom - 125](https://cloud.githubusercontent.com/assets/15208933/14061723/f1225ef0-f38f-11e5-899a-b84c15655288.png)

## Zoom 150% - BUG
![zoom - 150](https://cloud.githubusercontent.com/assets/15208933/14061725/f4a73564-f38f-11e5-8f70-c76ea4883c71.png)

## Zoom 200% - OK
![zoom - 200](https://cloud.githubusercontent.com/assets/15208933/14061727/f708b9fe-f38f-11e5-9b1d-1bc166b710eb.png)

**Comment by cpressland** [comment]
I run into the same issue on my Mac, I don't like to run Safari in full screen and have it at half width. Would be awesome to see this resolved, been meaning to log it for weeks.

**Comment by ssddanbrown** [comment]
The name should now cut down based on the length. If you're still seeing dodgy behaviour just give me a shout. :smiley:
