### ISSUE TITLE
Proxies / Help Guidance

### ISSUE THREAD

**Issue by armouredking** [ssddanbrown/BookStack#88]
Just FYI for documentation purposes. Laravel has no builtin way of solving HTTPS translation across a proxy. Save someone else the headache of trying to figure out why things aren't working.

[Fideloper](https://github.com/fideloper/TrustedProxy) has a project and it incorporated relatively painlessly into Bookstack ( tested by using email resets; prior to the install the email would set the address to http and after install the email reset links would be the correct https ).

**Comment by ssddanbrown** [comment]
Hi @armouredking,
Thanks for reporting this issue. Sorry for my very late reply, I did not fully understand this issue before. As of the latest bugfix releases, With the work done in #40, I don't believe this is an issue now. As long as you set the `APP_URL` line in the `.env` file to include your full base url including https BookStack will forcefully use that. I've given it a test via a proxy and all seems to work okay so I will close this issue.

If the above does not fix this let me know and we'll re-open this.
