### ISSUE TITLE
error 500, no log

### ISSUE THREAD

**Issue by tmos** [ssddanbrown/BookStack#91]
Hi,

I'm on a quite restrictive (don't hope any sudo) shared hosting, and I'm struggling with the installation.
I have all the required extensions, good php & mysql versions, and set up the directories well (I have to convess that I even set up some recursive 777 just for the try, but still nothing).

I don't have any logs or whatever appearing, so, I'm here, trying to get some help.
For your information I don't have much experience with Laravel.

Thanks you if you have time to give some help :),
Tom

**Comment by nwalke** [comment]
Were you able to follow all of the installation steps listed here?: https://www.bookstackapp.com/docs/admin/installation

**Comment by ssddanbrown** [comment]
Hi @tmos, as @nwalke said, Were you able to follow the installation steps without problems?

If so could you let us know what's showing when you try to access BookStack in the browser?

**Comment by tmos** [comment]
Hi,
Yes, I was able to go through all the steps of the installation without any blocking error. I did all this again, here are my steps, in order :

- cloning the repo : no warning, everything is ok
- `wget https://getcomposer.org/composer.phar`
- `chmod +x  composer.phar`
- then duplicate .env.example and change my db credentials (that are working with `mysql -h ...`)
-` php -d allow_url_fopen=on composer.phar install` , everything seems ok (without the -d, I can't download anything)
- ` chmod 777 storage/ bootstrap/cache/ public/uploads/` (I know, 777, but if it is working, I'll get those rigths down, this is just to be sure I don't have any right issue).
- `vim .htaccess` with :
```
Options +FollowSymLinks
RewriteEngine On

RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^ index.php [L]
```
- `php artisan migrate`, I confirm, says it's ok. Did it again, says nothing to migrate.

And then, I got a 500 internal error on my installation root.

Note that I set debug to true (still with production env), and Laravel is able to write in storage/logs (I got a log with a typo in a command), so maybe it can help for debug.

Thanks you for you help :)

**Comment by tmos** [comment]
Note that when I `php index.php ` in bash, I got :

```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="refresh" content="1;url=http://:/login" />

        <title>Redirecting to http://:/login</title>
    </head>
    <body>
        Redirecting to <a href="http://:/login">http://:/login</a>.
    </body>
</html>
```

It may help ?

**Comment by ssddanbrown** [comment]
Thanks @tmos for the extra details, Is the web-root pointing to the BookStack `/public` folder? The entry point to the application is the `public/index.php` file. 

You could try appending `/public` on the url in your browser (So the url will be `http://example.com/public`) and see what that shows to confirm the above.

As mentioned in the install instructions BookStack current has to be installed on its own domain (Or subdomain, It just has to be at the root of the url), and cannot be in a sub-folder.

**Comment by tmos** [comment]
My install is on wiki.example.com, and when I go to /public or /public/index.php, I also got a 500 internal error :(

**Comment by ssddanbrown** [comment]
@tmos Would you be able to say which hosts you are using? It would be useful to know exactly what versions of everything they are using. Also, there's a possibility someone's made a guide for installing laravel apps on that host.

**Comment by tmos** [comment]
We are hosted by a local company, I can have the software versions, but all requirements for php and mysql are surely respected (I double checked before starting the install). And php mods needed are enabled…

**Comment by ssddanbrown** [comment]
Hi @tmos , My apologies, I kind of forgot about this issue. Did you manage to solve this?

If not there some documentation here about debugging errors:
https://www.bookstackapp.com/docs/admin/debugging

Can you check if you have a laravel log, and if anything is in it, as mentioned in the above link.

**Comment by tmos** [comment]
Hi,
No problem, someone fixed it, I don't really know how, but he did... sorry not to have any more data about this, but this can be classified :)

Thanks for the help,
Tom
