### ISSUE TITLE
webroot documentation enchancment

### ISSUE THREAD

**Issue by vladware** [ssddanbrown/BookStack#93]
I don't know if it's just me but it took me a while to figure out I had to set the webroot to the public folder with nginx.

Initially I had `root /var/www/BookStack` but needed to do `root /var/www/BookStack/public`

Maybe a good idea to add it to the install instructions at the bottom for nginx.

**Comment by ssddanbrown** [comment]
@vladware Thanks for letting me know about this, Really surprised there was no mention of that in the installation docs. Will update the installation instructions soon.
