### ISSUE TITLE
Allow Bullet Points within Numbered Lists

### ISSUE THREAD

**Issue by cpressland** [ssddanbrown/BookStack#97]
Hi

If making a numbered list where there may be some subpoints in the from of bullet points the following number changes back to 1.

Example:

```
1. First Point
2. Second Point
    * Bullet Point 1
    * Bullet Point 2
1. Third Point
```

We can workaround this by manually replacing the `<ol>` tag with `<ol start="3">` or by deleting any additional `<ol>` tags and moving the `</ol>` to the end, but this isn't ideal and can be error prone for the end user.

**Comment by ssddanbrown** [comment]
Hi @cpressland , Could you confirm what editor you're using? The markdown or the standard WYSIWYG editor?

**Comment by cpressland** [comment]
Hi @ssddanbrown, WYSIWYG. Haven't tested with the Markdown editor yet.
