### ISSUE TITLE
Install failes

### ISSUE THREAD

**Issue by broedli** [ssddanbrown/BookStack#98]
Hi there,
I have one instance already running without any problems and wanted to set up another one but I fail at the last step.

It's probably something obvious but I don't get the error:
```
PHP Notice:  Undefined variable: redisConfig in /var/www/BookStack/config/database.php on line 142
```

Quick guidance for a blind man?

**Comment by ssddanbrown** [comment]
@broedli Sorry about this issue, Th error ran silent on my setup therefore went under my radar. I've just pushed out a bugfix release. Just update the instance via git and this should be sorted.

Let me know if the update does not fix this and I'll re-open.

**Comment by broedli** [comment]
looks good.
